package pkg

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lvim-tech/clipack/cnfg"
)

// integrationScript is the file a package leaves in its config directory for
// the shell to source. Only shell integration belongs in it; anything that only
// needs doing once goes in the package's setup script, which clipack runs.
const integrationScript = "config.sh"

// runSetup executes the one-off setup a package declares.
//
// It runs through a shell, like the build steps, so a registry entry can use
// quoting and conditionals. Failure is a warning: the program is installed and
// runnable, and a theme that did not get linked is not worth failing an install
// over — least of all after the manifest has been written.
func (in *Installer) runSetup(p *Package, paths Paths) {
	script := strings.TrimSpace(p.Install.Setup)
	if script == "" {
		return
	}

	in.infof("Running setup for %s", p.Name)
	if err := in.runCommand(script, paths.Base, nil); err != nil {
		in.warnf("setup for %s failed: %v", p.Name, err)
	}
}

// refreshShellIntegration rewrites the aggregate from what is on disk now.
//
// Regenerated rather than appended to, so removing a package takes its line
// with it. Reading the directory is what makes that work without a second
// record to keep in step with the first.
func (in *Installer) refreshShellIntegration() {
	configs := in.Config.Paths.Configs
	if configs == "" {
		return
	}

	scripts, err := installedIntegrations(configs)
	if err != nil {
		in.warnf("could not list the installed configurations: %v", err)
		return
	}

	path := cnfg.IntegrationPath(configs)
	if err := os.WriteFile(path, []byte(renderIntegration(configs, scripts)), 0o644); err != nil {
		in.warnf("could not write %s: %v", path, err)
	}
}

// installedIntegrations lists the packages whose config directory carries a
// config.sh, by name.
func installedIntegrations(configs string) ([]string, error) {
	entries, err := os.ReadDir(configs)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var names []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(configs, entry.Name(), integrationScript)); err != nil {
			continue
		}
		names = append(names, entry.Name())
	}

	// Sorted so the file is stable: an unordered directory read would rewrite it
	// with the same content in a different order on every install.
	sort.Strings(names)
	return names, nil
}

// renderIntegration builds the aggregate's contents.
//
// The configs directory is baked in as an absolute path rather than resolved at
// source time. Self-location needs ${0:a:h} in zsh and BASH_SOURCE in bash, and
// both are fatal syntax errors in a plain POSIX sh — while an absolute path
// works in every shell that can source the file at all. Moving the installation
// invalidates it, but moving the installation already means editing config.yaml
// and reinstalling, and any install regenerates this file.
func renderIntegration(configsDir string, names []string) string {
	var b strings.Builder

	b.WriteString("# Generated by clipack. Edits are lost on the next install or remove.\n")
	b.WriteString("#\n")
	b.WriteString("# Source this from your shell startup file once:\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("#   source %q\n", cnfg.IntegrationPath(configsDir)))
	b.WriteString("#\n")
	b.WriteString("# Every package installed afterwards is picked up without touching that\n")
	b.WriteString("# file again, and a package that is removed stops being sourced.\n")

	if len(names) == 0 {
		b.WriteString("\n# Nothing installed provides shell integration.\n")
		return b.String()
	}

	b.WriteString("\n")
	for _, name := range names {
		script := filepath.Join(configsDir, name, integrationScript)
		b.WriteString(fmt.Sprintf("[ -r %q ] && . %q\n", script, script))
	}

	// The && chain above leaves $? at 1 when the last file is unreadable, and a
	// sourced file's exit status becomes the shell's. true resets it.
	b.WriteString("true\n")
	return b.String()
}
